# Created by: Maxim Sobolev <sobomax@FreeBSD.org>
# $FreeBSD: head/devel/libsoup-gnome/Makefile 300896 2012-07-14 13:54:48Z beat $
#   $MCom: ports/trunk/devel/libsoup-gnome/Makefile 17268 2013-04-01 05:13:11Z marcus $

PORTREVISION=	0
CATEGORIES=	devel gnome
PKGNAMESUFFIX=	-gnome

MAINTAINER=	gnome@FreeBSD.org
COMMENT=	A GNOME wrapper for libsoup

MASTERDIR=	${.CURDIR}/../libsoup
DESCR=		${.CURDIR}/pkg-descr
PLIST=		${.CURDIR}/pkg-plist

SOUP_SLAVE=	yes

.include "${MASTERDIR}/Makefile"
