# Created by: Koop Mast <kwm@FreeBSD.org>
# $FreeBSD$

PORTNAME=	gnome-video-effects
PORTVERSION=	0.4.0
CATEGORIES=	graphics
MASTER_SITES=	GNOME

MAINTAINER=	kwm@FreeBSD.org
COMMENT=	A collection of Gstreamer effects

USES=		gettext pathfix
USE_XZ=		yes
USE_GNOME=	intlhack
USE_GMAKE=	yes
GNU_CONFIGURE=	yes

.include <bsd.port.mk>
