# Created by: Koop Mast <kwm@FreeBSD.org>
# $FreeBSD$

PORTNAME=	gnome-video-effects
PORTVERSION=	0.4.0
CATEGORIES=	graphics
MASTER_SITES=	GNOME

MAINTAINER=	kwm@FreeBSD.org
COMMENT=	Collection of Gstreamer effects

NO_STAGE=	yes
USES=		gettext gmake pathfix
USE_XZ=		yes
USE_GNOME=	intlhack
GNU_CONFIGURE=	yes

.include <bsd.port.mk>
