# Created by: Michael Johnson <ahze@FreeBSD.org>
# $FreeBSD$
#   $MCom: ports/graphics/gstreamer1-plugins-cairo/Makefile,v 1.1 2013/01/15 21:43:45 kwm Exp $

PORTREVISION=	0
CATEGORIES=	graphics

COMMENT=	Gstreamer vector graphics plugin

GST_PLUGIN=	cairo
DIST=		good

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer1-plugins

.include "${MASTERDIR}/Makefile"
