***************
*** 1,21 ****
- # New ports collection makefile for:		gmime2-sharp
- # Date Created:					20050513
- # Whom:				Tom McLaughlin <tmclaugh@sdf.lonestar.org>
- #
  # $FreeBSD: ports/mail/gmime24-sharp/Makefile,v 1.10 2012/06/01 05:21:27 dinoex Exp $
- #   $Id: Makefile,v 1.17 2006/10/26 18:37:29 tmclau02 Exp $
- #
  
  PORTREVISION=	2
  CATEGORIES=	mail
- PKGNAMESUFFIX=	-24-sharp
  
  MAINTAINER=	mono@FreeBSD.org
  COMMENT=	Mono bindings for gmime
  
- LIB_DEPENDS=	gmime-2.4:${PORTSDIR}/mail/gmime24
  
- MASTERDIR=	${.CURDIR}/../gmime24
  BUILD_WRKSRC=	${WRKSRC}/mono
  INSTALL_WRKSRC=	${BUILD_WRKSRC}
  DESCR=		${.CURDIR}/pkg-descr
--- 1,16 ----
+ # Created by:	Tom McLaughlin <tmclaugh@sdf.lonestar.org>
  # $FreeBSD: ports/mail/gmime24-sharp/Makefile,v 1.10 2012/06/01 05:21:27 dinoex Exp $
  
  PORTREVISION=	2
  CATEGORIES=	mail
+ PKGNAMESUFFIX=	-26-sharp
  
  MAINTAINER=	mono@FreeBSD.org
  COMMENT=	Mono bindings for gmime
  
+ LIB_DEPENDS=	gmime-2.6:${PORTSDIR}/mail/gmime26
  
+ MASTERDIR=	${.CURDIR}/../gmime26
  BUILD_WRKSRC=	${WRKSRC}/mono
  INSTALL_WRKSRC=	${BUILD_WRKSRC}
  DESCR=		${.CURDIR}/pkg-descr
