/* grilo-test.c generated by valac 0.18.0.28-4dffb, the Vala compiler
 * generated from grilo-test.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <grilo.h>
#include <stdlib.h>
#include <string.h>


#define TYPE_SIMPLE_PLAYLIST (simple_playlist_get_type ())
#define SIMPLE_PLAYLIST(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_SIMPLE_PLAYLIST, SimplePlaylist))
#define SIMPLE_PLAYLIST_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_SIMPLE_PLAYLIST, SimplePlaylistClass))
#define IS_SIMPLE_PLAYLIST(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_SIMPLE_PLAYLIST))
#define IS_SIMPLE_PLAYLIST_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_SIMPLE_PLAYLIST))
#define SIMPLE_PLAYLIST_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_SIMPLE_PLAYLIST, SimplePlaylistClass))

typedef struct _SimplePlaylist SimplePlaylist;
typedef struct _SimplePlaylistClass SimplePlaylistClass;
typedef struct _SimplePlaylistPrivate SimplePlaylistPrivate;
#define __g_list_free__g_object_unref0_0(var) ((var == NULL) ? NULL : (var = (_g_list_free__g_object_unref0_ (var), NULL)))
#define _g_main_loop_unref0(var) ((var == NULL) ? NULL : (var = (g_main_loop_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _SimplePlaylist {
	GObject parent_instance;
	SimplePlaylistPrivate * priv;
};

struct _SimplePlaylistClass {
	GObjectClass parent_class;
};

struct _SimplePlaylistPrivate {
	GList* source_list;
	GMainLoop* main_loop;
	gint processed_sources;
};


static gpointer simple_playlist_parent_class = NULL;

GType simple_playlist_get_type (void) G_GNUC_CONST;
#define SIMPLE_PLAYLIST_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_SIMPLE_PLAYLIST, SimplePlaylistPrivate))
enum  {
	SIMPLE_PLAYLIST_DUMMY_PROPERTY
};
static void _g_object_unref0_ (gpointer var);
static void _g_list_free__g_object_unref0_ (GList* self);
void simple_playlist_source_added_cb (SimplePlaylist* self, GrlSource* source);
void simple_playlist_source_removed_cb (SimplePlaylist* self, GrlSource* source);
SimplePlaylist* simple_playlist_new (void);
SimplePlaylist* simple_playlist_construct (GType object_type);
static void simple_playlist_search_cb (SimplePlaylist* self, GrlSource* source, guint operation_id, GrlMedia* media, guint remaining, GError* _error_);
void simple_playlist_search (SimplePlaylist* self, const gchar* q);
static void _simple_playlist_search_cb_grl_source_result_cb (GrlSource* source, guint operation_id, GrlMedia* media, guint remaining, gpointer self, GError* _error_);
void simple_playlist_run (SimplePlaylist* self);
gint simple_playlist_main (gchar** args, int args_length1);
static GObject * simple_playlist_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties);
static void _simple_playlist_source_added_cb_grl_registry_source_added (GrlRegistry* _sender, GrlSource* p0, gpointer self);
static void _simple_playlist_source_removed_cb_grl_registry_source_removed (GrlRegistry* _sender, GrlSource* p0, gpointer self);
static void simple_playlist_finalize (GObject* obj);


static void _g_object_unref0_ (gpointer var) {
	(var == NULL) ? NULL : (var = (g_object_unref (var), NULL));
}


static void _g_list_free__g_object_unref0_ (GList* self) {
	g_list_foreach (self, (GFunc) _g_object_unref0_, NULL);
	g_list_free (self);
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


void simple_playlist_source_added_cb (SimplePlaylist* self, GrlSource* source) {
	GrlSource* _tmp0_;
	GrlSupportedOps _tmp1_ = 0;
	GrlSupportedOps ops;
	GrlSupportedOps _tmp2_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (source != NULL);
	_tmp0_ = source;
	_tmp1_ = grl_source_supported_operations (_tmp0_);
	ops = _tmp1_;
	_tmp2_ = ops;
	if ((_tmp2_ & GRL_OP_SEARCH) != 0) {
		GrlSource* _tmp3_;
		const gchar* _tmp4_ = NULL;
		GrlSource* _tmp5_;
		GrlSource* _tmp6_;
		GList* _tmp7_;
		guint _tmp8_ = 0U;
		_tmp3_ = source;
		_tmp4_ = grl_source_get_name (_tmp3_);
		g_debug ("grilo-test.vala:23: Detected new source availabe: '%s' and it supports" \
" search", _tmp4_);
		_tmp5_ = source;
		_tmp6_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp5_, GRL_TYPE_SOURCE) ? ((GrlSource*) _tmp5_) : NULL);
		self->priv->source_list = g_list_append (self->priv->source_list, _tmp6_);
		_tmp7_ = self->priv->source_list;
		_tmp8_ = g_list_length (_tmp7_);
		g_debug ("grilo-test.vala:25: source list size = %u", _tmp8_);
	}
}


void simple_playlist_source_removed_cb (SimplePlaylist* self, GrlSource* source) {
	GrlSource* _tmp0_;
	const gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (source != NULL);
	_tmp0_ = source;
	_tmp1_ = grl_source_get_name (_tmp0_);
	g_debug ("grilo-test.vala:30: Source '%s' is gone", _tmp1_);
}


SimplePlaylist* simple_playlist_construct (GType object_type) {
	SimplePlaylist * self = NULL;
	self = (SimplePlaylist*) g_object_new (object_type, NULL);
	return self;
}


SimplePlaylist* simple_playlist_new (void) {
	return simple_playlist_construct (TYPE_SIMPLE_PLAYLIST);
}


static void simple_playlist_search_cb (SimplePlaylist* self, GrlSource* source, guint operation_id, GrlMedia* media, guint remaining, GError* _error_) {
	GError* _tmp0_;
	gboolean _tmp3_ = FALSE;
	GrlMedia* _tmp4_;
	gboolean _tmp9_;
	guint _tmp16_;
	gint _tmp20_;
	GList* _tmp21_;
	guint _tmp22_ = 0U;
	gint _tmp23_;
	GList* _tmp24_;
	guint _tmp25_ = 0U;
	g_return_if_fail (self != NULL);
	g_return_if_fail (source != NULL);
	_tmp0_ = _error_;
	if (_tmp0_ != NULL) {
		GError* _tmp1_;
		const gchar* _tmp2_;
		_tmp1_ = _error_;
		_tmp2_ = _tmp1_->message;
		g_critical ("grilo-test.vala:42: Error: %s", _tmp2_);
	}
	_tmp4_ = media;
	if (_tmp4_ != NULL) {
		gboolean _tmp5_ = FALSE;
		GrlMedia* _tmp6_;
		gboolean _tmp8_;
		_tmp6_ = media;
		if (G_TYPE_CHECK_INSTANCE_TYPE (_tmp6_, GRL_TYPE_MEDIA_AUDIO)) {
			_tmp5_ = TRUE;
		} else {
			GrlMedia* _tmp7_;
			_tmp7_ = media;
			_tmp5_ = G_TYPE_CHECK_INSTANCE_TYPE (_tmp7_, GRL_TYPE_MEDIA_VIDEO);
		}
		_tmp8_ = _tmp5_;
		_tmp3_ = _tmp8_;
	} else {
		_tmp3_ = FALSE;
	}
	_tmp9_ = _tmp3_;
	if (_tmp9_) {
		GrlMedia* _tmp10_;
		const gchar* _tmp11_ = NULL;
		gchar* _tmp12_;
		gchar* url;
		const gchar* _tmp13_;
		_tmp10_ = media;
		_tmp11_ = grl_media_get_url (_tmp10_);
		_tmp12_ = g_strdup (_tmp11_);
		url = _tmp12_;
		_tmp13_ = url;
		if (_tmp13_ != NULL) {
			GrlMedia* _tmp14_;
			const gchar* _tmp15_ = NULL;
			_tmp14_ = media;
			_tmp15_ = grl_media_get_url (_tmp14_);
			g_print ("%s\n", _tmp15_);
		}
		_g_free0 (url);
	}
	_tmp16_ = remaining;
	if (_tmp16_ == ((guint) 0)) {
		gint _tmp17_;
		GrlSource* _tmp18_;
		const gchar* _tmp19_ = NULL;
		_tmp17_ = self->priv->processed_sources;
		self->priv->processed_sources = _tmp17_ + 1;
		_tmp18_ = source;
		_tmp19_ = grl_source_get_name (_tmp18_);
		g_debug ("grilo-test.vala:54: %s finished", _tmp19_);
	}
	_tmp20_ = self->priv->processed_sources;
	_tmp21_ = self->priv->source_list;
	_tmp22_ = g_list_length (_tmp21_);
	g_debug ("grilo-test.vala:57: processed sources %d - source list size %u", _tmp20_, _tmp22_);
	_tmp23_ = self->priv->processed_sources;
	_tmp24_ = self->priv->source_list;
	_tmp25_ = g_list_length (_tmp24_);
	if (((guint) _tmp23_) == _tmp25_) {
		GMainLoop* _tmp26_;
		_tmp26_ = self->priv->main_loop;
		g_main_loop_quit (_tmp26_);
	}
}


static void _simple_playlist_search_cb_grl_source_result_cb (GrlSource* source, guint operation_id, GrlMedia* media, guint remaining, gpointer self, GError* _error_) {
	simple_playlist_search_cb (self, source, operation_id, media, remaining, _error_);
}


void simple_playlist_search (SimplePlaylist* self, const gchar* q) {
	GrlKeyID _tmp0_;
	GrlKeyID _tmp1_;
	GrlKeyID _tmp2_;
	GList* _tmp3_ = NULL;
	GList* keys;
	GrlCaps* caps;
	GrlCaps* _tmp4_;
	GrlOperationOptions* _tmp5_;
	GrlOperationOptions* options;
	GrlOperationOptions* _tmp6_;
	GrlOperationOptions* _tmp7_;
	GrlOperationOptions* _tmp8_;
	GList* _tmp9_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (q != NULL);
	_tmp0_ = GRL_METADATA_KEY_ID;
	_tmp1_ = GRL_METADATA_KEY_TITLE;
	_tmp2_ = GRL_METADATA_KEY_URL;
	_tmp3_ = grl_metadata_key_list_new (_tmp0_, _tmp1_, _tmp2_, NULL);
	keys = _tmp3_;
	caps = NULL;
	_tmp4_ = caps;
	_tmp5_ = grl_operation_options_new (_tmp4_);
	options = _tmp5_;
	_tmp6_ = options;
	grl_operation_options_set_skip (_tmp6_, (guint) 0);
	_tmp7_ = options;
	grl_operation_options_set_count (_tmp7_, 100);
	_tmp8_ = options;
	grl_operation_options_set_flags (_tmp8_, GRL_RESOLVE_FULL | GRL_RESOLVE_IDLE_RELAY);
	_tmp9_ = self->priv->source_list;
	{
		GList* source_collection = NULL;
		GList* source_it = NULL;
		source_collection = _tmp9_;
		for (source_it = source_collection; source_it != NULL; source_it = source_it->next) {
			GrlSource* _tmp10_;
			GrlSource* source = NULL;
			_tmp10_ = _g_object_ref0 ((GrlSource*) source_it->data);
			source = _tmp10_;
			{
				GrlSource* _tmp11_;
				const gchar* _tmp12_ = NULL;
				const gchar* _tmp13_;
				GrlSource* _tmp14_;
				const gchar* _tmp15_;
				GList* _tmp16_;
				GrlOperationOptions* _tmp17_;
				_tmp11_ = source;
				_tmp12_ = grl_source_get_name (_tmp11_);
				_tmp13_ = q;
				g_debug ("grilo-test.vala:72: %s - %s", _tmp12_, _tmp13_);
				_tmp14_ = source;
				_tmp15_ = q;
				_tmp16_ = keys;
				_tmp17_ = options;
				grl_source_search (_tmp14_, _tmp15_, _tmp16_, _tmp17_, _simple_playlist_search_cb_grl_source_result_cb, self);
				_g_object_unref0 (source);
			}
		}
	}
	_g_object_unref0 (options);
	_g_object_unref0 (caps);
}


void simple_playlist_run (SimplePlaylist* self) {
	GMainLoop* _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->main_loop;
	g_main_loop_run (_tmp0_);
}


gint simple_playlist_main (gchar** args, int args_length1) {
	gint result = 0;
	SimplePlaylist* _tmp0_;
	SimplePlaylist* playlist;
	gchar** _tmp1_;
	gint _tmp1__length1;
	const gchar* _tmp2_;
	grl_init (&args_length1, &args);
	_tmp0_ = simple_playlist_new ();
	playlist = _tmp0_;
	_tmp1_ = args;
	_tmp1__length1 = args_length1;
	_tmp2_ = _tmp1_[1];
	if (_tmp2_ != NULL) {
		SimplePlaylist* _tmp3_;
		gchar** _tmp4_;
		gint _tmp4__length1;
		const gchar* _tmp5_;
		SimplePlaylist* _tmp6_;
		_tmp3_ = playlist;
		_tmp4_ = args;
		_tmp4__length1 = args_length1;
		_tmp5_ = _tmp4_[1];
		simple_playlist_search (_tmp3_, _tmp5_);
		_tmp6_ = playlist;
		simple_playlist_run (_tmp6_);
	} else {
		g_print ("Query parameter missing\n");
	}
	result = 0;
	_g_object_unref0 (playlist);
	return result;
}


int main (int argc, char ** argv) {
	g_type_init ();
	return simple_playlist_main (argv, argc);
}


static void _simple_playlist_source_added_cb_grl_registry_source_added (GrlRegistry* _sender, GrlSource* p0, gpointer self) {
	simple_playlist_source_added_cb (self, p0);
}


static void _simple_playlist_source_removed_cb_grl_registry_source_removed (GrlRegistry* _sender, GrlSource* p0, gpointer self) {
	simple_playlist_source_removed_cb (self, p0);
}


static GObject * simple_playlist_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties) {
	GObject * obj;
	GObjectClass * parent_class;
	SimplePlaylist * self;
	GrlRegistry* _tmp0_ = NULL;
	GrlRegistry* _tmp1_;
	GrlRegistry* registry;
	GrlRegistry* _tmp2_;
	GrlRegistry* _tmp3_;
	GrlRegistry* _tmp4_;
	gboolean _tmp5_ = FALSE;
	gboolean _tmp6_;
	GError * _inner_error_ = NULL;
	parent_class = G_OBJECT_CLASS (simple_playlist_parent_class);
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_SIMPLE_PLAYLIST, SimplePlaylist);
	_tmp0_ = grl_registry_get_default ();
	_tmp1_ = _g_object_ref0 (_tmp0_);
	registry = _tmp1_;
	_tmp2_ = registry;
	g_signal_connect_object (_tmp2_, "source-added", (GCallback) _simple_playlist_source_added_cb_grl_registry_source_added, self, 0);
	_tmp3_ = registry;
	g_signal_connect_object (_tmp3_, "source-removed", (GCallback) _simple_playlist_source_removed_cb_grl_registry_source_removed, self, 0);
	_tmp4_ = registry;
	_tmp5_ = grl_registry_load_all_plugins (_tmp4_, &_inner_error_);
	_tmp6_ = _tmp5_;
	if (_inner_error_ != NULL) {
		_g_object_unref0 (registry);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
	}
	if (_tmp6_ == FALSE) {
		g_error ("grilo-test.vala:15: Failed to load plugins.");
	}
	_g_object_unref0 (registry);
	return obj;
}


static void simple_playlist_class_init (SimplePlaylistClass * klass) {
	simple_playlist_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (SimplePlaylistPrivate));
	G_OBJECT_CLASS (klass)->constructor = simple_playlist_constructor;
	G_OBJECT_CLASS (klass)->finalize = simple_playlist_finalize;
}


static void simple_playlist_instance_init (SimplePlaylist * self) {
	GMainLoop* _tmp0_;
	self->priv = SIMPLE_PLAYLIST_GET_PRIVATE (self);
	_tmp0_ = g_main_loop_new (NULL, FALSE);
	self->priv->main_loop = _tmp0_;
	self->priv->processed_sources = 0;
}


static void simple_playlist_finalize (GObject* obj) {
	SimplePlaylist * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_SIMPLE_PLAYLIST, SimplePlaylist);
	__g_list_free__g_object_unref0_0 (self->priv->source_list);
	_g_main_loop_unref0 (self->priv->main_loop);
	G_OBJECT_CLASS (simple_playlist_parent_class)->finalize (obj);
}


GType simple_playlist_get_type (void) {
	static volatile gsize simple_playlist_type_id__volatile = 0;
	if (g_once_init_enter (&simple_playlist_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (SimplePlaylistClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) simple_playlist_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (SimplePlaylist), 0, (GInstanceInitFunc) simple_playlist_instance_init, NULL };
		GType simple_playlist_type_id;
		simple_playlist_type_id = g_type_register_static (G_TYPE_OBJECT, "SimplePlaylist", &g_define_type_info, 0);
		g_once_init_leave (&simple_playlist_type_id__volatile, simple_playlist_type_id);
	}
	return simple_playlist_type_id__volatile;
}



